spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/careernavigator?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
        username: root
        password: 12345
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        static-path-pattern:   /static/**
    fox:
        swagger:
            enabled: true
    ai:
        openai:

            base-url: https://api.deepseek.com/
            api-key: sk-b6278be2badc4f2b83518c6dd71c402b
            chat:
                options:
                    model: deepseek-chat


mybatis:
    configuration:
        map-underscore-to-camel-case: true
